export interface Country {
    name: string;
    code: string;
    flag: string;
    languages: string[];
    warning?: string;
    dial_code?: string;
}

export const countries: Country[] = [
    {
        name: "Nigeria",
        code: "NG",
        flag: "🇳🇬",
        dial_code: "+234",
        languages: [
            "Hausa", "Yoruba", "Igbo", "English", "Pidgin English", "Fulfulde",
            "Kanuri", "Ibibio", "Tiv", "Ijaw", "Edo", "Annang", "Nupe", "Igala",
            "Idoma", "Itsekiri", "Urhobo", "Efik", "Gbagyi", "Ebira", "Sura",
            "Berom", "Tarok", "Eggon", "Bajju", "Jju", "Hyam", "Margi", "Bura",
            "Tangale", "Mumuye", "Jukun", "Bachama", "Higgi", "Kilba", "Chamba",
            "Verre", "Bata", "Longuda", "Bwatiye"
        ]
    },
    { name: "Afghanistan", code: "AF", warning: "Partially Supported", flag: "🇦🇫", dial_code: "+93", languages: ["Pashto", "Dari"] },
    { name: "Albania", code: "AL", flag: "🇦🇱", dial_code: "+355", languages: ["Albanian"] },
    { name: "Algeria", code: "DZ", flag: "🇩🇿", dial_code: "+213", languages: ["Arabic", "Berber", "French"] },
    { name: "Andorra", code: "AD", flag: "🇦🇩", dial_code: "+376", languages: ["Catalan"] },
    { name: "Angola", code: "AO", flag: "🇦🇴", dial_code: "+244", languages: ["Portuguese"] },
    { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", dial_code: "+1-268", languages: ["English"] },
    { name: "Argentina", code: "AR", flag: "🇦🇷", dial_code: "+54", languages: ["Spanish"] },
    { name: "Armenia", code: "AM", flag: "🇦🇲", dial_code: "+374", languages: ["Armenian"] },
    { name: "Australia", code: "AU", flag: "🇦🇺", dial_code: "+61", languages: ["English"] },
    { name: "Austria", code: "AT", flag: "🇦🇹", dial_code: "+43", languages: ["German"] },
    { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", dial_code: "+994", languages: ["Azerbaijani"] },
    { name: "Bahamas", code: "BS", flag: "🇧🇸", dial_code: "+1-242", languages: ["English"] },
    { name: "Bahrain", code: "BH", flag: "🇧🇭", dial_code: "+973", languages: ["Arabic"] },
    { name: "Bangladesh", code: "BD", flag: "🇧🇩", dial_code: "+880", languages: ["Bengali"] },
    { name: "Barbados", code: "BB", flag: "🇧🇧", dial_code: "+1-246", languages: ["English"] },
    { name: "Belarus", code: "BY", flag: "🇧🇾", dial_code: "+375", languages: ["Belarusian", "Russian"] },
    { name: "Belgium", code: "BE", flag: "🇧🇪", dial_code: "+32", languages: ["Dutch", "French", "German"] },
    { name: "Belize", code: "BZ", flag: "🇧🇿", dial_code: "+501", languages: ["English", "Spanish"] },
    { name: "Benin", code: "BJ", flag: "🇧🇯", dial_code: "+229", languages: ["French"] },
    { name: "Bhutan", code: "BT", flag: "🇧🇹", dial_code: "+975", languages: ["Dzongkha"] },
    { name: "Bolivia", code: "BO", flag: "🇧🇴", dial_code: "+591", languages: ["Spanish", "Quechua", "Aymara"] },
    { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", dial_code: "+387", languages: ["Bosnian", "Croatian", "Serbian"] },
    { name: "Botswana", code: "BW", flag: "🇧🇼", dial_code: "+267", languages: ["English", "Tswana"] },
    { name: "Brazil", code: "BR", flag: "🇧🇷", dial_code: "+55", languages: ["Portuguese"] },
    { name: "Brunei", code: "BN", flag: "🇧🇳", dial_code: "+673", languages: ["Malay"] },
    { name: "Bulgaria", code: "BG", flag: "🇧🇬", dial_code: "+359", languages: ["Bulgarian"] },
    { name: "Burkina Faso", code: "BF", flag: "🇧🇫", dial_code: "+226", languages: ["French"] },
    { name: "Burundi", code: "BI", flag: "🇧🇮", dial_code: "+257", languages: ["Kirundi", "French", "English"] },
    { name: "Cabo Verde", code: "CV", flag: "🇨🇻", dial_code: "+238", languages: ["Portuguese"] },
    { name: "Cambodia", code: "KH", flag: "🇰🇭", dial_code: "+855", languages: ["Khmer"] },
    { name: "Cameroon", code: "CM", flag: "🇨🇲", dial_code: "+237", languages: ["English", "French"] },
    { name: "Canada", code: "CA", flag: "🇨🇦", dial_code: "+1", languages: ["English", "French"] },
    { name: "Central African Republic", code: "CF", flag: "🇨🇫", dial_code: "+236", languages: ["Sango", "French"] },
    { name: "Chad", code: "TD", flag: "🇹🇩", dial_code: "+235", languages: ["Arabic", "French"] },
    { name: "Chile", code: "CL", flag: "🇨🇱", dial_code: "+56", languages: ["Spanish"] },
    { name: "China", code: "CN", flag: "🇨🇳", dial_code: "+86", languages: ["Mandarin Chinese"] },
    { name: "Colombia", code: "CO", flag: "🇨🇴", dial_code: "+57", languages: ["Spanish"] },
    { name: "Comoros", code: "KM", flag: "🇰🇲", dial_code: "+269", languages: ["Comorian", "Arabic", "French"] },
    { name: "Congo", code: "CG", flag: "🇨🇬", dial_code: "+242", languages: ["French"] },
    { name: "Costa Rica", code: "CR", flag: "🇨🇷", dial_code: "+506", languages: ["Spanish"] },
    { name: "Croatia", code: "HR", flag: "🇭🇷", dial_code: "+385", languages: ["Croatian"] },
    { name: "Cuba", code: "CU", flag: "🇨🇺", dial_code: "+53", languages: ["Spanish"] },
    { name: "Cyprus", code: "CY", flag: "🇨🇾", dial_code: "+357", languages: ["Greek", "Turkish"] },
    { name: "Czechia", code: "CZ", flag: "🇨🇿", dial_code: "+420", languages: ["Czech"] },
    { name: "Denmark", code: "DK", flag: "🇩🇰", dial_code: "+45", languages: ["Danish"] },
    { name: "Djibouti", code: "DJ", flag: "🇩🇯", dial_code: "+253", languages: ["Arabic", "French"] },
    { name: "Dominica", code: "DM", flag: "🇩🇲", dial_code: "+1-767", languages: ["English"] },
    { name: "Dominican Republic", code: "DO", flag: "🇩🇴", dial_code: "+1-809", languages: ["Spanish"] },
    { name: "Ecuador", code: "EC", flag: "🇪🇨", dial_code: "+593", languages: ["Spanish"] },
    { name: "Egypt", code: "EG", flag: "🇪🇬", dial_code: "+20", languages: ["Arabic"] },
    { name: "El Salvador", code: "SV", flag: "🇸🇻", dial_code: "+503", languages: ["Spanish"] },
    { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", dial_code: "+240", languages: ["Spanish", "French", "Portuguese"] },
    { name: "Eritrea", code: "ER", flag: "🇪🇷", dial_code: "+291", languages: ["Tigrinya", "Arabic", "English"] },
    { name: "Estonia", code: "EE", flag: "🇪🇪", dial_code: "+372", languages: ["Estonian"] },
    { name: "Eswatini", code: "SZ", flag: "🇸🇿", dial_code: "+268", languages: ["Swazi", "English"] },
    { name: "Ethiopia", code: "ET", flag: "🇪🇹", dial_code: "+251", languages: ["Amharic"] },
    { name: "Fiji", code: "FJ", flag: "🇫🇯", dial_code: "+679", languages: ["English", "Fijian", "Fiji Hindi"] },
    { name: "Finland", code: "FI", flag: "🇫🇮", dial_code: "+358", languages: ["Finnish", "Swedish"] },
    { name: "France", code: "FR", flag: "🇫🇷", dial_code: "+33", languages: ["French"] },
    { name: "Gabon", code: "GA", flag: "🇬🇦", dial_code: "+241", languages: ["French"] },
    { name: "Gambia", code: "GM", flag: "🇬🇲", dial_code: "+220", languages: ["English"] },
    { name: "Georgia", code: "GE", flag: "🇬🇪", dial_code: "+995", languages: ["Georgian"] },
    { name: "Germany", code: "DE", flag: "🇩🇪", dial_code: "+49", languages: ["German"] },
    { name: "Ghana", code: "GH", flag: "🇬🇭", dial_code: "+233", languages: ["English"] },
    { name: "Greece", code: "GR", flag: "🇬🇷", dial_code: "+30", languages: ["Greek"] },
    { name: "Grenada", code: "GD", flag: "🇬🇩", dial_code: "+1-473", languages: ["English"] },
    { name: "Guatemala", code: "GT", flag: "🇬🇹", dial_code: "+502", languages: ["Spanish"] },
    { name: "Guinea", code: "GN", flag: "🇬🇳", dial_code: "+224", languages: ["French"] },
    { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", dial_code: "+245", languages: ["Portuguese"] },
    { name: "Guyana", code: "GY", flag: "🇬🇾", dial_code: "+592", languages: ["English"] },
    { name: "Haiti", code: "HT", flag: "🇭🇹", dial_code: "+509", languages: ["French", "Haitian Creole"] },
    { name: "Honduras", code: "HN", flag: "🇭🇳", dial_code: "+504", languages: ["Spanish"] },
    { name: "Hungary", code: "HU", flag: "🇭🇺", dial_code: "+36", languages: ["Hungarian"] },
    { name: "Iceland", code: "IS", flag: "🇮🇸", dial_code: "+354", languages: ["Icelandic"] },
    { name: "India", code: "IN", flag: "🇮🇳", dial_code: "+91", languages: ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil", "Urdu", "Gujarati"] },
    { name: "Indonesia", code: "ID", flag: "🇮🇩", dial_code: "+62", languages: ["Indonesian"] },
    { name: "Iran", code: "IR", flag: "🇮🇷", dial_code: "+98", languages: ["Persian"] },
    { name: "Iraq", code: "IQ", flag: "🇮🇶", dial_code: "+964", languages: ["Arabic", "Kurdish"] },
    { name: "Ireland", code: "IE", flag: "🇮🇪", dial_code: "+353", languages: ["English", "Irish"] },
    { name: "Israel", code: "IL", flag: "🇮🇱", dial_code: "+972", languages: ["Hebrew"] },
    { name: "Italy", code: "IT", flag: "🇮🇹", dial_code: "+39", languages: ["Italian"] },
    { name: "Jamaica", code: "JM", flag: "🇯🇲", dial_code: "+1-876", languages: ["English"] },
    { name: "Japan", code: "JP", flag: "🇯🇵", dial_code: "+81", languages: ["Japanese"] },
    { name: "Jordan", code: "JO", flag: "🇯🇴", dial_code: "+962", languages: ["Arabic"] },
    { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", dial_code: "+7", languages: ["Kazakh", "Russian"] },
    { name: "Kenya", code: "KE", flag: "🇰🇪", dial_code: "+254", languages: ["Swahili", "English"] },
    { name: "Kiribati", code: "KI", flag: "🇰🇮", dial_code: "+686", languages: ["English", "Gilbertese"] },
    { name: "Korea (North)", code: "KP", flag: "🇰🇵", dial_code: "+850", languages: ["Korean"] },
    { name: "Korea (South)", code: "KR", flag: "🇰🇷", dial_code: "+82", languages: ["Korean"] },
    { name: "Kuwait", code: "KW", flag: "🇰🇼", dial_code: "+965", languages: ["Arabic"] },
    { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", dial_code: "+996", languages: ["Kyrgyz", "Russian"] },
    { name: "Laos", code: "LA", flag: "🇱🇦", dial_code: "+856", languages: ["Lao"] },
    { name: "Latvia", code: "LV", flag: "🇱🇻", dial_code: "+371", languages: ["Latvian"] },
    { name: "Lebanon", code: "LB", flag: "🇱🇧", dial_code: "+961", languages: ["Arabic"] },
    { name: "Lesotho", code: "LS", flag: "🇱🇸", dial_code: "+266", languages: ["Sesotho", "English"] },
    { name: "Liberia", code: "LR", flag: "🇱🇷", dial_code: "+231", languages: ["English"] },
    { name: "Libya", code: "LY", flag: "🇱🇾", dial_code: "+218", languages: ["Arabic"] },
    { name: "Liechtenstein", code: "LI", flag: "🇱🇮", dial_code: "+423", languages: ["German"] },
    { name: "Lithuania", code: "LT", flag: "🇱🇹", dial_code: "+370", languages: ["Lithuanian"] },
    { name: "Luxembourg", code: "LU", flag: "🇱🇺", dial_code: "+352", languages: ["Luxembourgish", "French", "German"] },
    { name: "Madagascar", code: "MG", flag: "🇲🇬", dial_code: "+261", languages: ["Malagasy", "French"] },
    { name: "Malawi", code: "MW", flag: "🇲🇼", dial_code: "+265", languages: ["English", "Chichewa"] },
    { name: "Malaysia", code: "MY", flag: "🇲🇾", dial_code: "+60", languages: ["Malay"] },
    { name: "Maldives", code: "MV", flag: "🇲🇻", dial_code: "+960", languages: ["Divehi"] },
    { name: "Mali", code: "ML", flag: "🇲🇱", dial_code: "+223", languages: ["French"] },
    { name: "Malta", code: "MT", flag: "🇲🇹", dial_code: "+356", languages: ["Maltese", "English"] },
    { name: "Marshall Islands", code: "MH", flag: "🇲🇭", dial_code: "+692", languages: ["Marshallese", "English"] },
    { name: "Mauritania", code: "MR", flag: "🇲🇷", dial_code: "+222", languages: ["Arabic"] },
    { name: "Mauritius", code: "MU", flag: "🇲🇺", dial_code: "+230", languages: ["English", "French"] },
    { name: "Mexico", code: "MX", flag: "🇲🇽", dial_code: "+52", languages: ["Spanish"] },
    { name: "Micronesia", code: "FM", flag: "🇫🇲", dial_code: "+691", languages: ["English"] },
    { name: "Moldova", code: "MD", flag: "🇲🇩", dial_code: "+373", languages: ["Romanian"] },
    { name: "Monaco", code: "MC", flag: "🇲🇨", dial_code: "+377", languages: ["French"] },
    { name: "Mongolia", code: "MN", flag: "🇲🇳", dial_code: "+976", languages: ["Mongolian"] },
    { name: "Montenegro", code: "ME", flag: "🇲🇪", dial_code: "+382", languages: ["Montenegrin"] },
    { name: "Morocco", code: "MA", flag: "🇲🇦", dial_code: "+212", languages: ["Arabic", "Berber"] },
    { name: "Mozambique", code: "MZ", flag: "🇲🇿", dial_code: "+258", languages: ["Portuguese"] },
    { name: "Myanmar", code: "MM", flag: "🇲🇲", dial_code: "+95", languages: ["Burmese"] },
    { name: "Namibia", code: "NA", flag: "🇳🇦", dial_code: "+264", languages: ["English"] },
    { name: "Nauru", code: "NR", flag: "🇳🇷", dial_code: "+674", languages: ["Nauruan", "English"] },
    { name: "Nepal", code: "NP", flag: "🇳🇵", dial_code: "+977", languages: ["Nepali"] },
    { name: "Netherlands", code: "NL", flag: "🇳🇱", dial_code: "+31", languages: ["Dutch"] },
    { name: "New Zealand", code: "NZ", flag: "🇳🇿", dial_code: "+64", languages: ["English", "Māori"] },
    { name: "Nicaragua", code: "NI", flag: "🇳🇮", dial_code: "+505", languages: ["Spanish"] },
    { name: "Niger", code: "NE", flag: "🇳🇪", dial_code: "+227", languages: ["French"] },
    { name: "North Macedonia", code: "MK", flag: "🇲🇰", dial_code: "+389", languages: ["Macedonian"] },
    { name: "Norway", code: "NO", flag: "🇳🇴", dial_code: "+47", languages: ["Norwegian"] },
    { name: "Oman", code: "OM", flag: "🇴🇲", dial_code: "+968", languages: ["Arabic"] },
    { name: "Pakistan", code: "PK", flag: "🇵🇰", dial_code: "+92", languages: ["Urdu", "English"] },
    { name: "Palau", code: "PW", flag: "🇵🇼", dial_code: "+680", languages: ["Palauan", "English"] },
    { name: "Panama", code: "PA", flag: "🇵🇦", dial_code: "+507", languages: ["Spanish"] },
    { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", dial_code: "+675", languages: ["English", "Hiri Motu", "Tok Pisin"] },
    { name: "Paraguay", code: "PY", flag: "🇵🇾", dial_code: "+595", languages: ["Spanish", "Guaraní"] },
    { name: "Peru", code: "PE", flag: "🇵🇪", dial_code: "+51", languages: ["Spanish"] },
    { name: "Philippines", code: "PH", flag: "🇵🇭", dial_code: "+63", languages: ["Filipino", "English"] },
    { name: "Poland", code: "PL", flag: "🇵🇱", dial_code: "+48", languages: ["Polish"] },
    { name: "Portugal", code: "PT", flag: "🇵🇹", dial_code: "+351", languages: ["Portuguese"] },
    { name: "Qatar", code: "QA", flag: "🇶🇦", dial_code: "+974", languages: ["Arabic"] },
    { name: "Romania", code: "RO", flag: "🇷🇴", dial_code: "+40", languages: ["Romanian"] },
    { name: "Russia", code: "RU", flag: "🇷🇺", dial_code: "+7", languages: ["Russian"] },
    { name: "Rwanda", code: "RW", flag: "🇷🇼", dial_code: "+250", languages: ["Kinyarwanda", "English", "French"] },
    { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", dial_code: "+1-869", languages: ["English"] },
    { name: "Saint Lucia", code: "LC", flag: "🇱🇨", dial_code: "+1-758", languages: ["English"] },
    { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", dial_code: "+1-784", languages: ["English"] },
    { name: "Samoa", code: "WS", flag: "🇼🇸", dial_code: "+685", languages: ["Samoan", "English"] },
    { name: "San Marino", code: "SM", flag: "🇸🇲", dial_code: "+378", languages: ["Italian"] },
    { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", dial_code: "+239", languages: ["Portuguese"] },
    { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", dial_code: "+966", languages: ["Arabic"] },
    { name: "Senegal", code: "SN", flag: "🇸🇳", dial_code: "+221", languages: ["French", "Wolof"] },
    { name: "Serbia", code: "RS", flag: "🇷🇸", dial_code: "+381", languages: ["Serbian"] },
    { name: "Seychelles", code: "SC", flag: "🇸🇨", dial_code: "+248", languages: ["English", "French", "Seychellois Creole"] },
    { name: "Sierra Leone", code: "SL", flag: "🇸🇱", dial_code: "+232", languages: ["English"] },
    { name: "Singapore", code: "SG", flag: "🇸🇬", dial_code: "+65", languages: ["English", "Malay", "Mandarin", "Tamil"] },
    { name: "Slovakia", code: "SK", flag: "🇸🇰", dial_code: "+421", languages: ["Slovak"] },
    { name: "Slovenia", code: "SI", flag: "🇸🇮", dial_code: "+386", languages: ["Slovene"] },
    { name: "Solomon Islands", code: "SB", flag: "🇸🇧", dial_code: "+677", languages: ["English"] },
    { name: "Somalia", code: "SO", flag: "🇸🇴", dial_code: "+252", languages: ["Somali", "Arabic"] },
    { name: "South Africa", code: "ZA", flag: "🇿🇦", dial_code: "+27", languages: ["Zulu", "Xhosa", "Afrikaans", "English"] },
    { name: "South Sudan", code: "SS", flag: "🇸🇸", dial_code: "+211", languages: ["English"] },
    { name: "Spain", code: "ES", flag: "🇪🇸", dial_code: "+34", languages: ["Spanish"] },
    { name: "Sri Lanka", code: "LK", flag: "🇱🇰", dial_code: "+94", languages: ["Sinhala", "Tamil"] },
    { name: "Sudan", code: "SD", flag: "🇸🇩", dial_code: "+249", languages: ["Arabic", "English"] },
    { name: "Suriname", code: "SR", flag: "🇸🇷", dial_code: "+597", languages: ["Dutch"] },
    { name: "Sweden", code: "SE", flag: "🇸🇪", dial_code: "+46", languages: ["Swedish"] },
    { name: "Switzerland", code: "CH", flag: "🇨🇭", dial_code: "+41", languages: ["German", "French", "Italian", "Romansh"] },
    { name: "Syria", code: "SY", flag: "🇸🇾", dial_code: "+963", languages: ["Arabic"] },
    { name: "Taiwan", code: "TW", flag: "🇹🇼", dial_code: "+886", languages: ["Mandarin Chinese"] },
    { name: "Tajikistan", code: "TJ", flag: "🇹🇯", dial_code: "+992", languages: ["Tajik"] },
    { name: "Tanzania", code: "TZ", flag: "🇹🇿", dial_code: "+255", languages: ["Swahili", "English"] },
    { name: "Thailand", code: "TH", flag: "🇹🇭", dial_code: "+66", languages: ["Thai"] },
    { name: "Timor-Leste", code: "TL", flag: "🇹🇱", dial_code: "+670", languages: ["Tetum", "Portuguese"] },
    { name: "Togo", code: "TG", flag: "🇹🇬", dial_code: "+228", languages: ["French"] },
    { name: "Tonga", code: "TO", flag: "🇹🇴", dial_code: "+676", languages: ["Tongan", "English"] },
    { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", dial_code: "+1-868", languages: ["English"] },
    { name: "Tunisia", code: "TN", flag: "🇹🇳", dial_code: "+216", languages: ["Arabic"] },
    { name: "Turkey", code: "TR", flag: "🇹🇷", dial_code: "+90", languages: ["Turkish"] },
    { name: "Turkmenistan", code: "TM", flag: "🇹🇲", dial_code: "+993", languages: ["Turkmen"] },
    { name: "Tuvalu", code: "TV", flag: "🇹🇻", dial_code: "+688", languages: ["Tuvaluan", "English"] },
    { name: "Uganda", code: "UG", flag: "🇺🇬", dial_code: "+256", languages: ["English", "Swahili"] },
    { name: "Ukraine", code: "UA", flag: "🇺🇦", dial_code: "+380", languages: ["Ukrainian"] },
    { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", dial_code: "+971", languages: ["Arabic"] },
    { name: "United Kingdom", code: "GB", flag: "🇬🇧", dial_code: "+44", languages: ["English"] },
    { name: "United States", code: "US", flag: "🇺🇸", dial_code: "+1", languages: ["English"] },
    { name: "Uruguay", code: "UY", flag: "🇺🇾", dial_code: "+598", languages: ["Spanish"] },
    { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", dial_code: "+998", languages: ["Uzbek"] },
    { name: "Vanuatu", code: "VU", flag: "🇻🇺", dial_code: "+678", languages: ["Bislama", "English", "French"] },
    { name: "Vatican City", code: "VA", flag: "🇻🇦", dial_code: "+379", languages: ["Italian", "Latin"] },
    { name: "Venezuela", code: "VE", flag: "🇻🇪", dial_code: "+58", languages: ["Spanish"] },
    { name: "Vietnam", code: "VN", flag: "🇻🇳", dial_code: "+84", languages: ["Vietnamese"] },
    { name: "Yemen", code: "YE", flag: "🇾🇪", dial_code: "+967", languages: ["Arabic"] },
    { name: "Zambia", code: "ZM", flag: "🇿🇲", dial_code: "+260", languages: ["English"] },
    { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", dial_code: "+263", languages: ["English", "Shona", "Ndebele"] }
];
