import * as fs from 'fs';

// -------------------------------------------------------------
// Script to test XUM AI Enterprise Task Creation API
// -------------------------------------------------------------

// REPLACE THESE WITH YOUR ACTUAL VALUES
const SUPABASE_URL = 'https://gkhemshbwmealgxczykk.supabase.co'; // e.g. https://xyz.supabase.co
const SUPABASE_API_KEY = 'sk_live_nGNlIT3_1Dppo0cNbDvs5Q_Ed7Zg-2r'; // the 'sk_live_...' or 'sk_test_...' generated by a company

async function testApiTaskCreation() {
  console.log('Starting API Test...');
  const endpoint = `${SUPABASE_URL}/functions/v1/api-v1-tasks`;

  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SUPABASE_API_KEY}`
      },
      body: JSON.stringify({
        title: "API Created Voice Task",
        description: "Please record this phrase.",
        task_type: "voice",
        reward: 1.50,
        target_count: 100,
        estimated_time: "5M"
      })
    });

    console.log(`Response Status: ${response.status}`);
    const data = await response.json();
    console.log('Response Body:', JSON.stringify(data, null, 2));

    if (response.ok) {
      console.log('✅ API Test Successful! Task logic correctly deducted the funds and logged the transaction.');
    } else {
      console.log('❌ API Test Failed or Returned Expected Error (e.g., 402 Payment Required for insufficient funds).');
    }

  } catch (error) {
    console.error('Network Error:', error);
  }
}

testApiTaskCreation();
